### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by qriouslad**
Fix Paypal button linking issue.

### CODE REVIEW

**Comment by kirtangajjar** [comment]
@qriouslad The paypal button was resolved with #855. If you're still interested, you can update the PR to only include "Develop and Deploy with EasyEngine + VVV + Wordmove" link. Otherwise, this PR should be marked as closed

**Comment by kirtangajjar** [comment]
cc @rahul286

**Comment by qriouslad** [comment]
@kirtangajjar Noted.

**Comment by rahul286** [comment]
I made required changes. Doing a manual merge. Thanks @qriouslad and @kirtangajjar

**Pull request merged**
