### PR TITLE
Upgrade to php7.0

### PR DESCRIPTION
**Pull request by gcnonato**
Attempt to upgrade from php5.6 to php-7.0

### CODE REVIEW

**Comment by harshadyeola** [comment]
@gcnonato 
Thanks for the pull request !! we will update on this soon :)

**Comment by gcnonato** [comment]
No problem, I hope it helps.

Cheers!

**Comment by gau1991** [comment]
Hello @gcnonato ,
Thanks for pull request. We are going to adding PHP 7.0 and PHP5.6 both support, so that user can run either PHP7.0, PHP 5.6, or both. 
So for now I am closing this pull request.

**Comment by MattyLB** [comment]
+1 to both. Thanks for your work, @gcnonato

**Comment by gino8080** [comment]
thank you I just updated to 3.5

how to update php version to 7?

**Pull request closed without merging**
