### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jhult**
Use direct Github link for installer instead of rt.cx domain

### CODE REVIEW

**Comment by mbtamuli** [comment]
@jhult Can you please explain why you think this PR is necessary?

**Comment by jhult** [comment]
Running a script pulled from a remote location can always be cause for concern. Users should always preview a script before they run it but many do not.

Using a third party domain, instead of pulling directly from GitHub, seems to further obfuscate something that doesn't need to be.

**Comment by rahul286** [comment]
@jhult rt.cx is not a third party domain. It is a first party domain, owned and managed by rtCamp - the company behind EasyEngine.

We need permalink for ease of readability and redirect users to correct versions. 

URL shortener can act as a permalink. It allows us to change installer script URL or even move installer to own GitHub repo later.

The users who are concerned about remote scripts can open short URL in the browser, which will redirect them to long URL version, review the script and proceed.

Sorry, we cannot accept this PR change.

**Comment by jhult** [comment]
I am aware of how permalinks work. I was simply recommending to not use one. The choice is yours.

If you are going to reference URLs, I would encourage you to be consistent (use all rt.cx or all githubusercontent.com). Right now, you link to both.

**Comment by rahul286** [comment]
We always prefer to use rt.cx links and so far there are only two links which we consider official:

1. rt.cx/ee points to v3 and is present on landing page https://easyengine.io/
2. rt.cx/ee4beta points to v4 beta

If you are talking about `.phar` link in [beta's readme file](https://github.com/EasyEngine/easyengine#linux), then it is a temporary link and doesn't have a short URL pointing to it. 

For any other links in readme/docs, feel free to send a PR opposite way! 🙂

**Pull request closed without merging**
