### PR TITLE
Fix ERR_SSL_PROTOCOL_ERROR due to nginx ciphers suite

### PR DESCRIPTION
**Pull request by VirtuBox**
- replace nginx ciphers-suite with the intermediate ciphers suite recommended by [Mozilla TLS Guidelines](https://mozilla.github.io/server-side-tls/ssl-config-generator/) to fix the issue 'ERR_SSL_PROTOCOL_ERROR' due to invalid ciphers with HTTP/2

### CODE REVIEW

**Comment by hermesmarcom** [comment]
This error also triggers ERR_SPDY_PROTOCOL_ERROR on Chrome and FireFox browser when accessing administration tool in https://site:22222
My working fix:
`ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;`

**Comment by VirtuBox** [comment]
Issues ERR_SPDY_PROTOCOL_ERROR and ERR_SSL_PROTOCOL_ERROR are fixed the with ciphers suite 
```
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
```

**Comment by mbtamuli** [comment]
@VirtuBox Can you please mention how I can reproduce the issue? Which version of Chrome/Firefox should I use to see these errors? Also, please mention your system info 
1. `lsb_release -a`
2. `uname -a`
3, `ee info`

**Comment by VirtuBox** [comment]
Hello @mbtamuli : 


1.  **Ubuntu 18.04 LTS** or **Ubuntu 16.04 LTS**
2. **Ubuntu 16.04 LTS** `Linux vps 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
**Ubuntu 18.04 LTS** `Linux vps 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
3. **Ubuntu 16.04 LTS** :
``` 
NGINX (1.14.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1
PHP5.6 is not installed
```
4. **Web Browsers** : Chrome 67, Opera 54, FireFox 61

5. **Step to reproduce the issue** : 
```
ee stack install

ee site create yourdomain.tld

ee site update yourdomain.tld --letsencrypt
```

I have tested few minutes ago to reproduce the issue on a fresh Ubuntu 16.04 LTS, and you can check yourself by visiting https://host.vtbox.pw/

**Comment by VirtuBox** [comment]
Hello @mbtamuli,

any updates about updating nginx ciphers suite ? 
Because there are now serveral threads about this issue on RtCamp community, and there are probably a lot users who cannot setup SSL on their server due to this HTTP/2 incompatible ciphers suite   : 

https://community.rtcamp.com/t/chrome-security-issue/8499
https://community.rtcamp.com/t/suggested-improvement-to-ssl-ciphers/10789

**Comment by rahul286** [comment]
Won't SSL be terminated at traefik.io now? 🤔

**Comment by janiosarmento** [comment]
> Won't SSL be terminated at traefik.io now? 🤔

What about current EEv3 users?

I understand your efforts should be focused on the new version, but severe issues (like cipher mismatches) should also be addressed in v3 with the same care.

**Comment by mbtamuli** [comment]
I will merge this tomorrow, once I have tested it out. Sorry for the delay @VirtuBox

**Comment by VirtuBox** [comment]
Hello @michacassola,

just run : 
```
sudo sed -i 's/ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHADHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!ECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;/ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS;/' /etc/nginx/nginx.conf

sudo service nginx reload
```

**Comment by michacassola** [comment]
Hi @VirtuBox ,
thanks! But isn't that nearly the same as what I wrote?

**Comment by VirtuBox** [comment]
Hello @michacassola,
that's exactly the same as what you wrote, sorry I did not read it properly.

**Pull request merged**
