### PR TITLE
Remove wp-cli autoloader 🥳

### PR DESCRIPTION
**Pull request by kirtangajjar**
There were some small code changes that had to be done in EE to remove autoload splitter. 

Other than that, we have to explicitly load files by passing them into the "files" section of autoload to load them correctly. I think autoload-splitter must have been including all the `.php` files in a repo previously, so we didn't need to do that before.

Linked PRs:
https://github.com/EasyEngine/site-command/pull/368
https://github.com/EasyEngine/site-type-php/pull/83
https://github.com/EasyEngine/site-type-wp/pull/190

https://github.com/EasyEngine/auth-command/pull/45
https://github.com/EasyEngine/cron-command/pull/50
https://github.com/EasyEngine/log-command/pull/6

### CODE REVIEW

**Comment by hAbd0u** [comment]
@kirtangajjar After I merged your PR and starts running the tests, I am getting this error:
```
PHP Fatal error:  Uncaught Error: Undefined constant "EE_ROOT_DIR" in /root/workspace/ee-kirtan/easyengine/vendor/easyengine/site-command/site-command.php:22
Stack trace:
#0 /root/workspace/ee-kirtan/easyengine/vendor/composer/autoload_real.php(73): require()
#1 /root/workspace/ee-kirtan/easyengine/vendor/composer/autoload_real.php(63): composerRequire1b926e6053d7e375658842c24d476370()
#2 /root/workspace/ee-kirtan/easyengine/vendor/autoload.php(7): ComposerAutoloaderInit1b926e6053d7e375658842c24d476370::getLoader()
#3 /root/workspace/ee-kirtan/easyengine/vendor/behat/behat/bin/behat(15): require('...')
#4 {main}
  thrown in /root/workspace/ee-kirtan/easyengine/vendor/easyengine/site-command/site-command.php on line 22
```
The include files is in order but still I don't get it why it is generating this error, even after I added to it this lines:
```
define( 'IS_DARWIN', 'Darwin' === php_uname( 's' ) );
if ( IS_DARWIN ) {
	define( 'EE_ROOT_DIR', rtrim( getenv( 'HOME' ), '/\\' ) . '/easyengine' );
} else {
	define( 'EE_ROOT_DIR', '/opt/easyengine' );
}
```  
I faced another error:
```
PHP Fatal error:  Uncaught Error: Call to undefined function EE\Utils\trailingslashit() in /root/workspace/ee-remove-autoloader/easyengine/vendor/easyengine/site-command/site-command.php:35
Stack trace:
#0 /root/workspace/ee-remove-autoloader/easyengine/vendor/composer/autoload_real.php(74): require()
#1 /root/workspace/ee-remove-autoloader/easyengine/vendor/composer/autoload_real.php(63): composerRequirec748de3f3f8082f9c48c31c816c5df47()
#2 /root/workspace/ee-remove-autoloader/easyengine/vendor/autoload.php(7): ComposerAutoloaderInitc748de3f3f8082f9c48c31c816c5df47::getLoader()
#3 /root/workspace/ee-remove-autoloader/easyengine/vendor/behat/behat/bin/behat(15): require('...')
#4 {main}
  thrown in /root/workspace/ee-remove-autoloader/easyengine/vendor/easyengine/site-command/site-command.php on line 35
```

**Comment by kirtangajjar** [comment]
@hAbd0u I'm not fully sure why you're facing these issues, but here are a few things you can look at or may help you in debugging further if you're interested:

1. Ensure your PHP version is 7.4. That's what we use while developing EE.
2. Check that all the linked PRs in my first comment are also checked out in your vendor directories.
3. Enable Xdebug and try to check it further with vscode.

**Comment by hAbd0u** [comment]
@kirtangajjar I tested it with both versions 7.4 and 8.0, and before doing that I merged the PRs in `vendor` directory first.
Any way, I made another [PR](https://github.com/EasyEngine/easyengine/pull/1510), please check it when you have time.

**Comment by hAbd0u** [comment]
@kirtangajjar Can you tell me why you didn't remove the bellow lines?
```
"autoload-splitter": {
	"splitter-logic": "EE\\AutoloadSplitter",
	"splitter-location": "php/EE/AutoloadSplitter.php",
	"split-target-prefix-true": "autoload_commands",
	"split-target-prefix-false": "autoload_framework"
}
```
Because I am having hard time [here ](https://github.com/hAbd0u/easyengine/commit/0d805ba799f133375419027cd2d7bc160f614ece)trying to find the correct order for autoloading.

**Review by mrrobot47 — APPROVED** [review]

**Pull request merged**
